// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//!
//! PostgreSQL。占位符是**编号**的 `$n`（与 `?` 类方言的关键区别）。

use super::DialectSpec;
use super::InsertPlan;
use super::Limit;
use crate::entity::ColType;

pub(crate) struct PostgresSpec;

impl DialectSpec for PostgresSpec {
    fn quote(&self, ident: &str) -> String {
        format!("\"{ident}\"")
    }

    fn placeholder(&self, index: usize) -> String {
        format!("${index}")
    }

    fn limit_clause(&self, limit: u64, offset: u64, _has_order: bool) -> Limit {
        Limit {
            prefix: String::new(),
            suffix: if offset == 0 {
                format!(" LIMIT {limit}")
            } else {
                format!(" LIMIT {limit} OFFSET {offset}")
            },
        }
    }

    fn insert_plan(&self, table: &str, cols: &[String], pk: &str, _n_params: usize) -> InsertPlan {
        // PG 原生支持 RETURNING —— 一步式，无 MySQL 的连接作用域问题。
        InsertPlan::Single {
            sql: format!(
                "INSERT INTO {} ({}) VALUES ({}) RETURNING {}",
                self.quote(table),
                cols.iter()
                    .map(|c| self.quote(c))
                    .collect::<Vec<_>>()
                    .join(", "),
                (1..=cols.len())
                    .map(|i| self.placeholder(i))
                    .collect::<Vec<_>>()
                    .join(", "),
                self.quote(pk)
            ),
        }
    }

    fn upsert(&self, table: &str, cols: &[String], pk: &str, _n_params: usize) -> String {
        let assigns = cols
            .iter()
            .filter(|c| c.as_str() != pk)
            .map(|c| {
                let q = self.quote(c);
                format!("{q} = excluded.{q}")
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO UPDATE SET {assigns}",
            self.quote(table),
            cols.iter()
                .map(|c| self.quote(c))
                .collect::<Vec<_>>()
                .join(", "),
            (1..=cols.len())
                .map(|i| self.placeholder(i))
                .collect::<Vec<_>>()
                .join(", "),
            self.quote(pk)
        )
    }

    fn bool_literal(&self, b: bool) -> String {
        if b { "TRUE".into() } else { "FALSE".into() }
    }

    fn col_type(&self, ty: ColType) -> String {
        match ty {
            ColType::I64 => "BIGINT".into(),
            ColType::I32 => "INTEGER".into(),
            ColType::F64 => "DOUBLE PRECISION".into(),
            ColType::Bool => "BOOLEAN".into(),
            ColType::Text | ColType::Json => "TEXT".into(),
            ColType::Bytes => "BYTEA".into(),
            // **必须是 TIMESTAMPTZ，不是 TIMESTAMP** —— 后者丢掉时区，
            // 写入的 UTC 会被按本地时区解读（矩阵明确要求）。
            ColType::Timestamp => "TIMESTAMPTZ".into(),
            ColType::Date => "DATE".into(),
        }
    }

    fn table_exists_sql(&self, table: &str) -> String {
        format!("CREATE TABLE IF NOT EXISTS {}", self.quote(table))
    }

    fn autoincrement_ddl(&self, ty: ColType) -> String {
        // 矩阵：自增主键用 BIGSERIAL（等价于 BIGINT + 序列 + 默认值）。
        match ty {
            ColType::I64 => "BIGSERIAL".into(),
            other => format!("{} GENERATED BY DEFAULT AS IDENTITY", self.col_type(other)),
        }
    }

    fn max_params_per_stmt(&self) -> usize {
        // PostgreSQL 的协议上限就是 65535（u16）。
        65535
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::ColType;

    fn s() -> PostgresSpec {
        PostgresSpec
    }

    #[test]
    fn quotes_with_double_quotes() {
        assert_eq!(s().quote("user"), "\"user\"");
    }

    /// `$n` 是**编号**占位符 —— 下标必须有意义，与 `?` 类方言的关键区别。
    #[test]
    fn placeholder_is_numbered() {
        assert_eq!(s().placeholder(1), "$1");
        assert_eq!(s().placeholder(7), "$7");
    }

    #[test]
    fn limit_is_a_suffix() {
        assert_eq!(s().limit_clause(10, 0, false).suffix, " LIMIT 10");
        assert_eq!(
            s().limit_clause(10, 20, false).suffix,
            " LIMIT 10 OFFSET 20"
        );
        assert_eq!(s().limit_clause(10, 0, false).prefix, "");
    }

    #[test]
    fn placeholders_are_sequential_in_insert() {
        let plan = s().insert_plan("users", &["a".into(), "b".into()], "id", 2);
        match plan {
            InsertPlan::Single { sql } => {
                assert_eq!(
                    sql,
                    "INSERT INTO \"users\" (\"a\", \"b\") VALUES ($1, $2) RETURNING \"id\""
                );
            }
            other => panic!("PG 应走一步式 RETURNING，得到 {other:?}"),
        }
    }

    #[test]
    fn upsert_uses_on_conflict() {
        let sql = s().upsert("users", &["id".into(), "name".into()], "id", 2);
        assert!(sql.contains("ON CONFLICT (\"id\")"), "got: {sql}");
        assert!(
            sql.contains("DO UPDATE SET \"name\" = excluded.\"name\""),
            "got: {sql}"
        );
    }

    #[test]
    fn upsert_never_assigns_the_pk() {
        let sql = s().upsert("users", &["id".into(), "name".into()], "id", 2);
        assert!(!sql.contains("\"id\" = excluded"), "主键不该被更新: {sql}");
    }

    #[test]
    fn bool_literal_is_true_false() {
        assert_eq!(s().bool_literal(true), "TRUE");
        assert_eq!(s().bool_literal(false), "FALSE");
    }

    #[test]
    fn column_types_match_the_matrix() {
        assert_eq!(s().col_type(ColType::Timestamp), "TIMESTAMPTZ");
        assert_eq!(s().col_type(ColType::Text), "TEXT");
        assert_eq!(s().col_type(ColType::Date), "DATE");
        assert_eq!(s().col_type(ColType::Bytes), "BYTEA");
    }

    #[test]
    fn autoincrement_reuses_the_bigserial_identity() {
        assert!(
            s().autoincrement_ddl(ColType::I64).contains("BIGSERIAL")
                || s().autoincrement_ddl(ColType::I64).contains("IDENTITY"),
            "got: {}",
            s().autoincrement_ddl(ColType::I64)
        );
    }

    #[test]
    fn max_params_is_the_pg_limit() {
        assert_eq!(s().max_params_per_stmt(), 65535);
    }
}
