// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//!
//! ANSI 近似方言。也是第三方 `SqlExecutor` 未声明方言时的回退。

use super::DialectSpec;
use super::InsertPlan;
use super::Limit;
use crate::entity::ColType;

pub(crate) struct StandardSpec;

impl DialectSpec for StandardSpec {
    fn quote(&self, ident: &str) -> String {
        format!("\"{ident}\"")
    }

    fn placeholder(&self, _index: usize) -> String {
        "?".into()
    }

    fn limit_clause(&self, limit: u64, offset: u64, _has_order: bool) -> Limit {
        let suffix = if offset == 0 {
            format!(" LIMIT {limit}")
        } else {
            format!(" LIMIT {limit} OFFSET {offset}")
        };
        Limit {
            prefix: String::new(),
            suffix,
        }
    }

    fn insert_plan(&self, table: &str, cols: &[String], pk: &str, _n_params: usize) -> InsertPlan {
        let cols_sql = cols
            .iter()
            .map(|c| self.quote(c))
            .collect::<Vec<_>>()
            .join(", ");
        let ph = (1..=cols.len())
            .map(|i| self.placeholder(i))
            .collect::<Vec<_>>()
            .join(", ");
        InsertPlan::Single {
            sql: format!(
                "INSERT INTO {} ({cols_sql}) VALUES ({ph}) RETURNING {}",
                self.quote(table),
                self.quote(pk)
            ),
        }
    }

    fn upsert(&self, table: &str, cols: &[String], pk: &str, _n_params: usize) -> String {
        let cols_sql = cols
            .iter()
            .map(|c| self.quote(c))
            .collect::<Vec<_>>()
            .join(", ");
        let ph = (1..=cols.len())
            .map(|i| self.placeholder(i))
            .collect::<Vec<_>>()
            .join(", ");
        let assigns = cols
            .iter()
            .filter(|c| c.as_str() != pk)
            .map(|c| {
                let q = self.quote(c);
                format!("{q} = excluded.{q}")
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "INSERT INTO {} ({cols_sql}) VALUES ({ph}) ON CONFLICT ({}) DO UPDATE SET {assigns}",
            self.quote(table),
            self.quote(pk)
        )
    }

    fn bool_literal(&self, b: bool) -> String {
        if b { "TRUE".into() } else { "FALSE".into() }
    }

    fn col_type(&self, ty: ColType) -> String {
        match ty {
            ColType::I64 => "BIGINT".into(),
            ColType::I32 => "INTEGER".into(),
            ColType::F64 => "DOUBLE PRECISION".into(),
            ColType::Bool => "BOOLEAN".into(),
            ColType::Text | ColType::Json => "TEXT".into(),
            ColType::Bytes => "BLOB".into(),
            ColType::Timestamp => "TIMESTAMP".into(),
            ColType::Date => "DATE".into(),
        }
    }

    fn table_exists_sql(&self, table: &str) -> String {
        format!("CREATE TABLE IF NOT EXISTS {}", self.quote(table))
    }

    fn autoincrement_ddl(&self, ty: ColType) -> String {
        format!("{} GENERATED BY DEFAULT AS IDENTITY", self.col_type(ty))
    }

    fn max_params_per_stmt(&self) -> usize {
        65535
    }
}
