[package]
name = "helloworld"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hello World example for the e-cat framework"
publish = false

[dependencies]
ecat = { version = "6.0.0", path = "../../ecat" }
ecat-transport-http = { version = "6.0.0", path = "../../ecat-transport-http" }
ecat-transport-grpc = { version = "6.0.0", path = "../../ecat-transport-grpc" }
ecat-logging = { version = "6.0.0", path = "../../ecat-logging" }
ecat-middleware = { version = "6.0.0", path = "../../ecat-middleware" }
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower.workspace = true
tracing.workspace = true
axum.workspace = true
