[package]
name = "ecat-transport-ws"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebSocket transport implementation for e-cat"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ecat-transport = { version = "5.0.0", path = "../ecat-transport" }
tokio = { workspace = true, features = ["net", "sync", "rt", "time", "macros"] }
async-trait.workspace = true
axum = { workspace = true, features = ["ws"] }
tower.workspace = true
futures-util = "0.3"
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "io-util"] }
