[package]
name = "websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebSocket example for the e-cat framework"
publish = false

[dependencies]
ecat = { version = "6.0.0", path = "../../ecat" }
ecat-transport-ws = { version = "6.0.0", path = "../../ecat-transport-ws" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
