[package]
name = "ecat-logging"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Structured logging via tracing for e-cat"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
ecat-tracing = { version = "4.0.0", path = "../ecat-tracing" }
