[package]
name = "ecat-lock"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Distributed lock abstraction for e-cat"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "sync"] }
