[package]
name = "ecat-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
ecat-metadata = { path = "../ecat-metadata" }
ecat-encoding = { path = "../ecat-encoding" }
ecat-errors = { path = "../ecat-errors" }
tower.workspace = true
tokio.workspace = true
async-trait.workspace = true
http = "1"
bytes = "1"
